### ISSUE TITLE
Update Footer design and small issues around the site. 

### ISSUE THREAD

**Issue by kamruzzaman-dev** [devofthought/travel-and-bus-management#103]
1. update content and design on the footer.
2. social logo radius `rounded` 
3. add `newsfeed` on the footer section. here is a simple...
![image](https://github.com/devofthought/travel-and-bus-management/assets/95479332/cde8194e-f07f-4520-b5b3-c4769de370c1)
4.`Our Top Buses` section convert margin to padding.
5.`Technologies Used` section move to beforte footer section.

**Comment by Ankan112** [comment]
All task have been done :)
